# Lecture Plan

1. Data Prep
2. Vertex AI Training
3. Vertex AI Testing

---

In [ ]:
! pip install pandas nltk

In [3]:
import pandas as pd

df = pd.read_csv('C:/TrainingMaterial/generative-ai/genai-material/training-data.csv')

df.head(10)

                                                Text Category
0  I'm interested in upgrading my internet plan. ...    Sales
1  I'm having trouble with my internet connection...  Service
2  What are your internet speeds like? I'm consid...  General
3  I want to know more about your internet packag...    Sales
4  My internet bill seems higher than usual this ...  Service
5  I'm moving to a new apartment next month and n...    Sales
6  I'm experiencing slow speeds with my current i...  Service
7  What are your customer service hours? I need h...  Service
8  I'm interested in upgrading my internet plan. ...    Sales
9  My internet is down again. This is the third t...  Service

In [4]:
# lowercase
df['Text'] = df['Text'].str.lower()

df.head(10)

                                                Text Category
0  i'm interested in upgrading my internet plan. ...    Sales
1  i'm having trouble with my internet connection...  Service
2  what are your internet speeds like? i'm consid...  General
3  i want to know more about your internet packag...    Sales
4  my internet bill seems higher than usual this ...  Service
5  i'm moving to a new apartment next month and n...    Sales
6  i'm experiencing slow speeds with my current i...  Service
7  what are your customer service hours? i need h...  Service
8  i'm interested in upgrading my internet plan. ...    Sales
9  my internet is down again. this is the third t...  Service

In [5]:
# remove whitespaces

def remove_whitespaces(text):
    return ' '.join(text.split())

df['Text'] = df['Text'].apply(remove_whitespaces)

df.head(10)

                                                Text Category
0  i'm interested in upgrading my internet plan. ...    Sales
1  i'm having trouble with my internet connection...  Service
2  what are your internet speeds like? i'm consid...  General
3  i want to know more about your internet packag...    Sales
4  my internet bill seems higher than usual this ...  Service
5  i'm moving to a new apartment next month and n...    Sales
6  i'm experiencing slow speeds with my current i...  Service
7  what are your customer service hours? i need h...  Service
8  i'm interested in upgrading my internet plan. ...    Sales
9  my internet is down again. this is the third t...  Service

In [6]:
# tokenize
import nltk

nltk.download('punkt')

from nltk import word_tokenize

df['Text'] = df['Text'].apply(word_tokenize)

df.head(10)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\KrishnaGopikaUrlagan\AppData\Roaming\nltk_dat
[nltk_data]     a...
[nltk_data]   Package punkt is already up-to-date!

                                                Text Category
0  [i, 'm, interested, in, upgrading, my, interne...    Sales
1  [i, 'm, having, trouble, with, my, internet, c...  Service
2  [what, are, your, internet, speeds, like, ?, i...  General
3  [i, want, to, know, more, about, your, interne...    Sales
4  [my, internet, bill, seems, higher, than, usua...  Service
5  [i, 'm, moving, to, a, new, apartment, next, m...    Sales
6  [i, 'm, experiencing, slow, speeds, with, my, ...  Service
7  [what, are, your, customer, service, hours, ?,...  Service
8  [i, 'm, interested, in, upgrading, my, interne...    Sales
9  [my, internet, is, down, again, ., this, is, t...  Service

In [7]:
# remove stopwords

nltk.download('stopwords')

from nltk.corpus import stopwords

en_stopwords = stopwords.words('english')

def remove_stopwords(text):

    result = []

    for token in text:
        if token not in en_stopwords:
            result.append(token)

    return result

df['Text'] = df['Text'].apply(lambda x: remove_stopwords(x))

df.head(10)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\KrishnaGopikaUrlagan\AppData\Roaming\nltk_dat
[nltk_data]     a...
[nltk_data]   Package stopwords is already up-to-date!

                                                Text Category
0  ['m, interested, upgrading, internet, plan, .,...    Sales
1  ['m, trouble, internet, connection, ., keeps, ...  Service
2  [internet, speeds, like, ?, 'm, considering, s...  General
3  [want, know, internet, packages, ., send, info...    Sales
4  [internet, bill, seems, higher, usual, month, ...  Service
5  ['m, moving, new, apartment, next, month, need...    Sales
6  ['m, experiencing, slow, speeds, current, inte...  Service
7  [customer, service, hours, ?, need, help, bill...  Service
8  ['m, interested, upgrading, internet, plan, .,...    Sales
9  [internet, ., third, time, week, ., please, fi...  Service